language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7


env:
  - TARGET=buildJar
  - TARGET=test
  - ANT_OPTS="-Xmx2048m"

script: ant -buildfile ./Compiler/build/build.xml $TARGET

notifications:
  email:
    - compiler@lara.coderworks.de
