language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7


env:
  - TARGET=buildJar
  - TARGET=runUnitTests
  - TARGET=runIntegrationTests-compile

script: ANT_OPTS="-Xmx2048m" ant -buildfile ./Compiler/build/build.xml $TARGET

notifications:
  email:
    - compiler@lara.coderworks.de
